### ISSUE TITLE
Credential flow-Test-auth is not found

### ISSUE THREAD

**Issue by wade0317** [FlowCI/flow-agent-x#18]
![image](https://user-images.githubusercontent.com/3960813/75962748-4d03fd80-5eff-11ea-8e4e-42cbb903ddae.png)

UI Error

**Comment by gy2006** [comment]
可以看一下 yaml 配置嘛？

应该是获取 git repo 的分支信息时，没有找到名为 ‘flow-Test-auth’ 的证书，可以看一下这个文档试试
https://github.com/FlowCI/docs/blob/master/v1.0/git/github.md
